blank_issues_enabled: false
contact_links:
  - name: Contact the repository owner
    url: https://github.com/matt-wigg
    about:  For any questions or inquiries, please reach out to the repository owner.
